#!/bin/bash
# file: .devcontainer/additions/start-otel-monitoring-supervisor.sh
#
# DESCRIPTION: Supervisord-compatible startup script for OpenTelemetry monitoring services
# PURPOSE: Starts OTel collectors and script_exporter as supervised services
#
# Usage: This script is called by supervisord, not directly
#
#------------------------------------------------------------------------------
# SERVICE METADATA - For supervisord service discovery
#------------------------------------------------------------------------------

SERVICE_NAME="OTel Monitoring"
SERVICE_DESCRIPTION="Start devcontainer monitoring services when connected to our network"
SERVICE_CATEGORY="INFRA_CONFIG"
CHECK_RUNNING_COMMAND="pgrep -f 'otelcol-contrib.*--config' >/dev/null 2>&1"
SERVICE_LOG_PATH_LIFECYCLE="/var/log/otelcol-lifecycle.log"
SERVICE_LOG_PATH_METRICS="/var/log/otelcol-metrics.log"
SERVICE_CONFIG_PATH="$HOME/.devcontainer-identity"

# IMPORTANT: This service uses a GROUP configuration
# Instead of a single SERVICE_COMMAND, it defines multiple programs
SERVICE_TYPE="group"
SERVICE_PRIORITY="30"
SERVICE_PROGRAMS="script-exporter,otel-lifecycle,otel-metrics"
SERVICE_AUTO_RESTART="true"

#------------------------------------------------------------------------------
# CONFIGURATION
#------------------------------------------------------------------------------

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

log_info() { echo -e "${BLUE}ℹ️  $1${NC}"; }
log_success() { echo -e "${GREEN}✅ $1${NC}"; }
log_warn() { echo -e "${YELLOW}⚠️  $1${NC}"; }
log_error() { echo -e "${RED}❌ $1${NC}"; }

#------------------------------------------------------------------------------
# SUPERVISORD CONFIGURATION GENERATION
#------------------------------------------------------------------------------

generate_supervisor_config() {
    local config_file="/etc/supervisor/conf.d/otel-monitoring-group.conf"
    
    log_info "Generating supervisord configuration for OTel Monitoring..."
    
    # Source identity file to get environment variables
    if [ -f "$HOME/.devcontainer-identity" ]; then
        # shellcheck source=/dev/null
        source "$HOME/.devcontainer-identity"
    else
        log_error "Identity file not found: $HOME/.devcontainer-identity"
        echo ""
        echo "Run: bash .devcontainer/additions/config-devcontainer-identity.sh"
        exit 1
    fi
    
    # Generate TS_HOSTNAME if not provided
    if [ -z "${TS_HOSTNAME:-}" ]; then
        TS_HOSTNAME="dev-${DEVELOPER_ID:-unknown}-${PROJECT_NAME:-unknown}"
    fi
    
    # Create the supervisor config
    sudo tee "$config_file" > /dev/null << EOF
# OpenTelemetry Monitoring Services Group
# Auto-generated by start-otel-monitoring-supervisor.sh

[program:script-exporter]
command=/workspace/.devcontainer/additions/supervisor-wrappers/script-exporter-wrapper.sh
autostart=true
autorestart=true
priority=30
user=vscode
stdout_logfile=/var/log/supervisor/script-exporter.log
stderr_logfile=/var/log/supervisor/script-exporter-error.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
startsecs=5
stopwaitsecs=10

[program:otel-lifecycle]
command=/workspace/.devcontainer/additions/supervisor-wrappers/otel-lifecycle-wrapper.sh
autostart=true
autorestart=true
priority=31
user=vscode
environment=DEVELOPER_ID="${DEVELOPER_ID:-}",DEVELOPER_EMAIL="${DEVELOPER_EMAIL:-}",PROJECT_NAME="${PROJECT_NAME:-}",TS_HOSTNAME="${TS_HOSTNAME}"
stdout_logfile=/var/log/supervisor/otel-lifecycle.log
stderr_logfile=/var/log/supervisor/otel-lifecycle-error.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
startsecs=5
stopwaitsecs=10
depends_on=script-exporter

[program:otel-metrics]
command=/workspace/.devcontainer/additions/supervisor-wrappers/otel-metrics-wrapper.sh
autostart=true
autorestart=true
priority=32
user=vscode
environment=DEVELOPER_ID="${DEVELOPER_ID:-}",DEVELOPER_EMAIL="${DEVELOPER_EMAIL:-}",PROJECT_NAME="${PROJECT_NAME:-}",TS_HOSTNAME="${TS_HOSTNAME}"
stdout_logfile=/var/log/supervisor/otel-metrics.log
stderr_logfile=/var/log/supervisor/otel-metrics-error.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
startsecs=5
stopwaitsecs=10
depends_on=script-exporter

[group:otel-monitoring]
programs=script-exporter,otel-lifecycle,otel-metrics
priority=30
EOF

    # Make wrapper scripts executable
    chmod +x /workspace/.devcontainer/additions/supervisor-wrappers/*.sh
    
    log_success "Supervisord configuration generated"
    
    # Reload supervisor
    if pgrep supervisord > /dev/null; then
        log_info "Reloading supervisor..."
        sudo supervisorctl reread
        sudo supervisorctl update
        log_success "Services should now be starting"
    else
        log_warn "Supervisord not running - start it with: sudo /etc/init.d/supervisord start"
    fi
}

#------------------------------------------------------------------------------
# MAIN
#------------------------------------------------------------------------------

main() {
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "🔧 Configuring OTel Monitoring for Supervisord"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    
    generate_supervisor_config
    
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "✅ Configuration Complete"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "🔧 Management:"
    echo "   dev-services status                    # Show all services"
    echo "   dev-services restart otel-monitoring:* # Restart all OTel services"
    echo "   dev-services restart otel-lifecycle    # Restart lifecycle collector"
    echo "   dev-services restart otel-metrics      # Restart metrics collector"
    echo "   dev-services restart script-exporter   # Restart script exporter"
    echo "   dev-services logs otel-lifecycle       # View lifecycle logs"
    echo "   dev-services logs otel-metrics         # View metrics logs"
    echo ""
}

main "$@"
